### ISSUE TITLE
License, and uploading to Overleaf and ShareLatex

### ISSUE THREAD

**Issue by phcerdan** [hcalitz/MasseyLatexTemplates#1]
Hey @hcalitz, hope you are doing good.
we are having a latex workshop today at Massey: https://github.com/phcerdan/workshop_intro_latex

We might be using cloud services for teaching purposes and also because it is easy to start wth. Overleaf, and in the future probably ShareLatex.
It would be cool if we provide Massey templates there, and your beamer is really cool. Would it be possible for me to upload it here, and make some modifications maybe? I might fork this repo, but not sure about the license of your work. Can you upload a MIT or APACHE License.txt?

Cheers,
Pablo

**Comment by hcalitz** [comment]
Hi Pablo

Have fun... it was developed for use and  improvement by Massey people.  No license.  Free to use and to change.

Hannes

**Comment by phcerdan** [comment]
Awesome, thanks!

**Comment by phcerdan** [comment]
Note that no license defaults to be copyrighted by you, if you want it to be free, you have to put a license (MIT, BSD, APACHE, and a few others). I know it is contradictory!

Thanks Hannes

**Comment by hcalitz** [comment]
Thanks for the info.  Will look into it as soon as time allows.

**Comment by phcerdan** [comment]
No worries for this case, but you might find it useful in the future.

**Comment by hcalitz** [comment]
Ok, Uploaded the license.  Never too old to learn. I should pay more attention to legal stuff I assume :) Have a great workshop!

**Comment by phcerdan** [comment]
Thx Hannes, the workshop was nice, maybe we converted some of them from Word... will see :)
